apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jl4im49nz-dotnet-basic
  janus-idp.io/tekton: jl4im49nz-dotnet-basic
  backstage.io/kubernetes-id: jl4im49nz-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jl4im49nz-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
